name: Daily Extension Commit

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
          pip install requests
          python generate_extension_entry.py

      - name: Commit and Push
        run: |
          git config user.name "AI Extension Bot"
          git config user.email "bot@example.com"
          git add extensions/
          git commit -m "Daily Extension Commit - $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
